## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ostrovnoy,RU,68.0531,39.5131,20.35,95,74,11.88,broken clouds
1,1,Hilo,US,19.7297,-155.0900,77.25,79,24,7.00,few clouds
2,2,Varzea Da Palma,BR,-17.5981,-44.7308,70.63,74,31,1.34,scattered clouds
3,3,Corum,TR,40.5000,34.7500,19.26,55,100,3.58,overcast clouds
4,4,Filingue,NE,14.3521,3.3168,78.66,18,29,12.03,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Hilo,US,19.7297,-155.0900,77.25,79,24,7.00,few clouds
2,2,Varzea Da Palma,BR,-17.5981,-44.7308,70.63,74,31,1.34,scattered clouds
4,4,Filingue,NE,14.3521,3.3168,78.66,18,29,12.03,scattered clouds
8,8,Inhambane,MZ,-23.8650,35.3833,75.29,89,18,10.45,light rain
9,9,Mount Darwin,ZW,-16.7725,31.5838,62.56,88,99,3.80,overcast clouds
10,10,Mataura,NZ,-46.1927,168.8643,61.48,60,68,9.48,broken clouds
15,15,Loon,PH,9.7998,123.7929,81.88,80,96,1.45,overcast clouds
16,16,East London,ZA,-33.0153,27.9116,72.25,86,46,13.58,scattered clouds
17,17,Ilheus,BR,-14.7889,-39.0494,74.97,86,30,1.88,scattered clouds
20,20,Lorengau,PG,-2.0226,147.2712,85.05,68,31,4.25,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                371
City                   371
Country                367
Lat                    371
Lng                    371
Max Temp               371
Humidity               371
Cloudiness             371
Wind Speed             371
Current Description    371
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Hilo,US,77.25,few clouds,19.7297,-155.0900,
2,Varzea Da Palma,BR,70.63,scattered clouds,-17.5981,-44.7308,
4,Filingue,NE,78.66,scattered clouds,14.3521,3.3168,
8,Inhambane,MZ,75.29,light rain,-23.8650,35.3833,
9,Mount Darwin,ZW,62.56,overcast clouds,-16.7725,31.5838,
10,Mataura,NZ,61.48,broken clouds,-46.1927,168.8643,
15,Loon,PH,81.88,overcast clouds,9.7998,123.7929,
16,East London,ZA,72.25,scattered clouds,-33.0153,27.9116,
17,Ilheus,BR,74.97,scattered clouds,-14.7889,-39.0494,
20,Lorengau,PG,85.05,scattered clouds,-2.0226,147.2712,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [9]:
# 7. Drop the rows where there is no Hotel Name.
# Remove rows from hotel_df DataFrame that do NOT have values in "Hotel Name" column.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!=""]
clean_hotel_df.head(50)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Hilo,US,77.25,few clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
2,Varzea Da Palma,BR,70.63,scattered clouds,-17.5981,-44.7308,Casa Fernandes
8,Inhambane,MZ,75.29,light rain,-23.8650,35.3833,Oceano
10,Mataura,NZ,61.48,broken clouds,-46.1927,168.8643,Ellie's Villa
15,Loon,PH,81.88,overcast clouds,9.7998,123.7929,Ladressner's
16,East London,ZA,72.25,scattered clouds,-33.0153,27.9116,Tu Casa
17,Ilheus,BR,74.97,scattered clouds,-14.7889,-39.0494,Barravento Hotel
20,Lorengau,PG,85.05,scattered clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
21,Najran,SA,65.05,few clouds,17.4924,44.1277,محمد هادي ال فطيح
24,Port Blair,IN,84.24,mist,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
25,Port Alfred,ZA,71.46,overcast clouds,-33.5906,26.8910,The Halyards Hotel
32,Boyolangu,ID,85.89,broken clouds,-8.1181,111.8935,Yos ega cv
33,Rikitea,PF,78.84,clear sky,-23.1203,-134.9692,People ThankYou
34,Nouadhibou,MR,64.38,sand,20.9310,-17.0347,El Medina
36,Kavaratti,IN,81.99,few clouds,10.5669,72.6420,Hotels in Lakshadweep Islands
39,Busselton,AU,78.31,clear sky,-33.6500,115.3333,Observatory Guest House
41,Touros,BR,79.18,overcast clouds,-5.1989,-35.4608,INN NEW HORIZON
43,Hobart,AU,73.27,few clouds,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
45,Hermanus,ZA,65.80,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
48,Diourbel,SN,76.21,clear sky,14.6628,-16.3925,ISFAR maison Blanche
49,Balikpapan,ID,82.40,broken clouds,-1.2675,116.8289,Swiss-Belhotel Balikpapan
52,Robertsport,LR,79.47,light rain,6.7533,-11.3686,Kwepunha Retreat
53,Hanmer Springs,NZ,68.67,scattered clouds,-42.5167,172.8167,The Chalets Motel
56,Tshikapa,CD,71.62,light rain,-6.4167,20.8000,Hôtel Tshia-Muntu de Tshikapa
57,Cockburn Town,TC,77.74,clear sky,21.4612,-71.1419,Osprey Beach Hotel
61,Esperance,AU,76.84,overcast clouds,-33.8667,121.9000,Hospitality Esperance
62,Sao Joao Da Barra,BR,78.03,clear sky,-21.6403,-41.0511,Pousada Porto De Canoas
64,Puerto Ayora,EC,76.55,scattered clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
65,Kaitangata,NZ,63.86,broken clouds,-46.2817,169.8464,Kaitangata Motor Camp
66,Vaini,TO,86.16,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
67,Yining,CN,75.61,broken clouds,29.0361,114.5636,Xiushui Hotel
68,Cidreira,BR,69.62,overcast clouds,-30.1811,-50.2056,Hotel Castelo
70,Nueva Gorgona,PA,78.58,clear sky,8.5500,-79.8667,Coronado Luxury Club & Suites
72,Bluff,NZ,61.81,few clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
79,Paka,MY,82.33,scattered clouds,4.6374,103.4368,RUMBIA RESORT VILLA Paka Terengganu
83,Dingle,PH,87.39,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
86,Lahaina,US,79.84,few clouds,20.8783,-156.6825,Lahaina Shores Beach Resort
87,Kapaa,US,79.12,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
88,New Plymouth,NZ,65.32,overcast clouds,-39.0667,174.0833,Belt Road Seaside Holiday Park
89,Ahipara,NZ,71.62,overcast clouds,-35.1667,173.1667,Ahipara Holiday Park
90,Kongolo,CD,68.81,overcast clouds,-5.3833,27.0000,GUEST HOUSE OASIS
91,Rodrigues Alves,BR,73.02,broken clouds,-7.7380,-72.6509,Pousada Aconchego
92,Pacasmayo,PE,73.58,scattered clouds,-7.4006,-79.5714,Hotel Libertad
93,Avarua,CK,82.45,broken clouds,-21.2078,-159.7750,Paradise Inn
95,Sanchor,IN,79.84,clear sky,24.7553,71.7722,Hotel Amar Palace & AC Restaurant
96,Castro,BR,64.15,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
97,Mumford,GH,80.01,broken clouds,5.2618,-0.7590,Spanish Villa
98,Sola,VU,82.69,overcast clouds,-13.8833,167.5500,Leumerus Bungalows
99,Bandarbeyla,SO,76.93,overcast clouds,9.4942,50.8122,JABIR HOTEL
100,Kassala,SD,68.58,broken clouds,15.4510,36.4000,Amassi Hotel Gash

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "./WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))